### ISSUE TITLE
Some extension project fail with 'has no file' error message.

### ISSUE THREAD

**Issue by robertcsakany** [s4u/sign-maven-plugin#105]
**Describe the bug**
Some extension project fail with 'has no file' error message.

There are some module in multi module project which have no jar artifact, uses karaf-feature extension plugin.

**To Reproduce**

Create a project with     

`
<artifactId>osgi-asciidoc-converter-karaf-features</artifactId>
<packaging>feature</packaging>
`

where the parent project contains the sign plugin definition.

`
[ERROR] Failed to execute goal org.simplify4u.plugins:sign-maven-plugin:0.3.1:sign (default) on project osgi-asciidoc-converter-karaf-features: Execution default of goal org.simplify4u.plugins:sign-maven-plugin:0.3.1:sign failed: Artifact: hu.blackbelt:osgi-asciidoc-converter-karaf-features:feature:1.0.0.20211221_210526_f25d548e_feature_JNG_3407_AddNewGPGAndTagAction has no file -> [Help 1]
`

**Expected behavior**

Build have to be success

**Comment by slawekjaranowski** [comment]
can you provide example project with `packaging` `feature`

**Comment by robertcsakany** [comment]
Yes, sure. I need a little time to make an example.

**Comment by slawekjaranowski** [comment]
a workaround you can put in your module without file

```
    <properties>
        <sign.skip>true</sign.skip>
    </properties>
```

**Comment by robertcsakany** [comment]
Okay. I made the little sample project to reproduce. 
[example-bug-105.zip](https://github.com/s4u/sign-maven-plugin/files/7761583/example-bug-105.zip)

The interesting part when only the feature project is presented, everythin is fine. When I've added the API - means the sign plugin was executed - failed. 

Thank you your idea for skip, I'm trying it.

**Comment by robertcsakany** [comment]
@slawekjaranowski The workaround is working fine, the other modules of project is not causes any error.

**Comment by slawekjaranowski** [comment]
For reference: https://issues.apache.org/jira/browse/MINSTALL-151
