### ISSUE TITLE
EdDSA KeyFactory not available

### ISSUE THREAD

**Issue by josevjunior** [s4u/sign-maven-plugin#110]
**Describe the bug**
Using the plugin to sing a jar throws the exception: org.bouncycastle.openpgp.PGPException: Exception constructing key: EdDSA KeyFactory not available

**To Reproduce**

Executing maven clean install with the following plugin configuration

                     <plugin>
                        <groupId>org.simplify4u.plugins</groupId>
                        <artifactId>sign-maven-plugin</artifactId>
                        <version>1.0.0</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <keyFile></keyFile>
                                    <keyId></keyId>
                                    <keyPass></keyPass>
                                </configuration>
                            </execution>                            
                        </executions>
                    </plugin>

**Expected behavior**
Sign the jar

**Additional context**
OS: Windows 10
JDK: Oracle 1.8

**Comment by slawekjaranowski** [comment]
Can you provide a command / steps to generate EdDSA key for testing purpose?

**Comment by electricsam** [comment]
I just ran into this as well.  I was following this guide: https://central.sonatype.org/publish/requirements/gpg/.  The default key was EdDSA when I ran "gpg --gen-key".  It looks like you can choose the key type if you run "gpg --full-generate-key".

I'm running this on a Mac.
