### ISSUE TITLE
releases 0.1.0 and 0.2.0 are not reproducible

### ISSUE THREAD

**Issue by hboutemy** [s4u/sign-maven-plugin#27]
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/simplify4u/plugins/sign-maven-plugin/sign-maven-plugin-0.1.0.diffoscope

it seems sisu-maven-plugin version used doe not contain https://github.com/eclipse/sisu.inject/pull/5

**Comment by mkarg** [comment]
This is already fixed since https://github.com/s4u/sign-maven-plugin/pull/26/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8.

**Comment by hboutemy** [comment]
yes, it just requires to update the plugin to version 0.3.4

**Comment by hboutemy** [comment]
(and yes, there is some magic in the library to generate inject file from the compiler, without even using a Maven plugin: I forgot that...)

**Comment by slawekjaranowski** [comment]
@hboutemy - version `0.2.1` should be reproducible

**Comment by hboutemy** [comment]
yes, it is https://github.com/jvm-repo-rebuild/reproducible-central#org.simplify4u.plugins:sign-maven-plugin
kudos :)
