### ISSUE TITLE
[Feature] Add option to fail if the key cannot be found/signing cannot be done

### ISSUE THREAD

**Issue by andrebrait** [s4u/sign-maven-plugin#47]
**Is your feature request related to a problem? Please describe.**
I want my build to fail if I somehow forget to add the signing key or if signing somehow fails.

**Describe the solution you'd like**
Add an option to prevent the signing goal to be skipped in case we're missing the key/pass (environment) variables.

**Describe alternatives you've considered**
Nothing.

**Additional context**
This is useful for preventing the build from succeeding if it's being done for publishing releases when signing is required.

**Comment by slawekjaranowski** [comment]
there is option: `skipNoKey` - https://www.simplify4u.org/sign-maven-plugin/sign-mojo.html#skipNoKey

Did you try use it?

**Comment by andrebrait** [comment]
Oops. I swear I searched for it. Ok, closing this.
